#!/bin/csh -fb

set orders = ( \
    "Odelta0" "Odelta2" "Odelta3" \
	)


set files = `ls $argv`

foreach arg ( $files )
     foreach order ( $orders )
	    echo "***** Converting file $arg to order $order."
	    set output = `echo $arg| sed -e "s/CCC/$order/g"`
	    sed -e "s/CCC/$order/g"  $arg > $output
     end   
     echo ""
end

echo "***** Done."

