#!/bin/csh -fb

set energies = ( \
    "001" "002" "003" "004" "005" "010" "015" "020" "025" "030" "040" \
	)

set files = `ls $argv`

foreach arg ( $files )
     foreach energy ( $energies )
	echo "***** Converting file $arg to energy $energy."
	set output = `echo $arg| sed -e "s/AAA/$energy/g" `
        sed -e "s/AAA/$energy/g" $arg > $output   
     end   
     echo ""
end

echo "***** Done."

